# Generated by Django 4.0.6 on 2022-07-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='form_user',
            new_name='from_user',
        ),
    ]
